### ISSUE TITLE
package.json's main file doesn't exist

### ISSUE THREAD

**Issue by nickdaugherty** [Simperium/node-simperium#20]
`package.json` defines `main` as `./lib/simperium/index.js`, which no longer exists, which breaks all `require()`s that use this module.

https://github.com/Simperium/node-simperium/blob/f98cbbdef27213e3a5f387c242812bac251e7bda/package.json#L5

**Comment by joshbetz** [comment]
Jinx. #21 fixes this.

**Comment by nickdaugherty** [comment]
This appears to be happening only at tag `0.2.0`, as that was tagged before the `postinstall` and related code was checked in...so the ES transpiling stuff never happens and `lib/...` never exists.

Installing the latest `HEAD` worked for me, so I think the `0.2.0` tag needs to be moved, because it's broken as-is.

**Comment by nickdaugherty** [comment]
By the way, this issue came up because the `vip` tag somehow was reset to an old commit (before Node 4.x compatibility), which started breaking all our tests. We decided to try upgrading to `0.2.0`, but that was also broken.

**Comment by beaucollins** [comment]
The npm package now has the transpiled code.

I'm not sure why the `vip` tag was changed but I'm sure it's my fault.
