### ISSUE TITLE
Publication on npm?

### ISSUE THREAD

**Issue by jpetitcolas** [Simperium/node-simperium#28]
Would it be possible to publish this package on npm, to be able to install it using a simple:

``` sh
npm install --save node-simperium
```

Thanks! :)

**Comment by beaucollins** [comment]
Yes, definitely.

The only thing to take into consideration is publishing the transpiled code after removing the babel dependencies in your #27 PR.

**Comment by beaucollins** [comment]
Done! https://www.npmjs.com/package/simperium
