### ISSUE TITLE
Default storage and bucket update() arity mismatch

### ISSUE THREAD

**Issue by nickdaugherty** [Simperium/node-simperium#29]
On `update()`, the Bucket calls `update()` on the store, but the arity of the two does not match, which means the `callback` argument is not a function, triggering this error:

```
TypeError: callback is not a function
    at BucketStore.update (./node_modules/simperium/lib/simperium/storage/default.js:23:2)
    at Bucket.update (./node_modules/simperium/lib/simperium/bucket.js:44:20)
    at Bucket.Channel.bucket.update (./node_modules/simperium/lib/simperium/channel.js:255:17)
```

Bucket:

```
Bucket.prototype.update = function( id, data, options, callback ) {
	if ( typeof options === 'function' ) {
		callback = options;
	}
	return this.store.update( id, data, callback );
};
```
https://github.com/Simperium/node-simperium/blob/6c401c0cccd909b756df6fce492f88545f2ea656/src/simperium/bucket.js#L27-L32

Default Store:

```
BucketStore.prototype.update = function( id, object, isIndexing, callback ) {
	this.objects[id] = object;
	callback( null, {id: id, data: object, isIndexing: isIndexing} );
};
```

https://github.com/Simperium/node-simperium/blob/6c401c0cccd909b756df6fce492f88545f2ea656/src/simperium/storage/default.js#L13-L16

Note the extra `isIndexing` argument on the Store that the Bucket isn't sending.

**Comment by beaucollins** [comment]
I'll want to double-check some things. There's an indirection happening in the `Channel` object that injects itself between a `Bucket` and `BucketStore`:

https://github.com/Simperium/node-simperium/blob/6c401c0cccd909b756df6fce492f88545f2ea656/src/simperium/channel.js#L235-L250
